version: 2.1

executors:
  docker-publisher:
    docker:
      # https://github.com/CircleCI-Public/cimg-base
      - image: cimg/base:current

jobs:
  build-and-publish:
    parameters:
      docker-tag:
        type: string
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Log time
          command: date
      - run:
          name: Gen Docker file
          command: |
            FOLDER_PREFIX=$(support/FOLDER_PREFIX.sh)
            FOLDER=${FOLDER_PREFIX}<< parameters.docker-tag >>
            ./build.sh << parameters.docker-tag >>
            ls -la ${FOLDER}
            echo "###"
            echo "# --- Dockerfile Content ---"
            echo "###"
            cat ${FOLDER}/Dockerfile
      - run:
          name: build Docker image
          command: |
            VERSION=$(support/VERSION.sh)
            FOLDER_PREFIX=$(support/FOLDER_PREFIX.sh)
            IMAGE_NAME=$(support/targetImage.sh)
            BUILD_VERSION=<< parameters.docker-tag >>
            BUILD_FOLDER=${FOLDER_PREFIX}<< parameters.docker-tag >>
            BUILD_ARG=""
            if [ "x$VERSION" == "x$BUILD_VERSION" ]; then
                BUILD_ARG="--build-arg ALT_VERSION=fpm-alpine3.14"
            fi
            docker build ${BUILD_ARG} -f ${BUILD_FOLDER}/Dockerfile \
              -t $IMAGE_NAME:${BUILD_VERSION} \
              ./${BUILD_FOLDER}
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            ./compile.sh p << parameters.docker-tag >>
  trigger-pmvc:
    executor: docker-publisher
    steps:
      - run:
          name: Trigger pmvc to test docker image
          # https://app.circleci.com/settings/user/tokens
          command: |
            curl -X POST --url https://circleci.com/api/v2/project/github/pmvc/pmvc/pipeline \
               --header "Content-Type: application/json" \
               --header "Circle-Token: $CIRCLE_TOKEN"

workflows:
  run-job:
    jobs:
      - build-and-publish:
          matrix:
            parameters:
              docker-tag:
                ["8.1", "8.0", "7.4", "7.3", "7.2", "7.1", "7.0", "5.6", "5.5"]
      - trigger-pmvc:
          requires:
            - build-and-publish
  nightly:
    jobs:
      - trigger-pmvc
    triggers:
      - schedule:
          cron: "0 0 1 * *"
          filters:
            branches:
              only:
                - main
