version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: hillliu/pmvc-phpunit
    docker:
      - image: circleci/buildpack-deps:18.04

jobs:
  build-and-publish:
    parameters:
      docker-tag:
        type: string
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Gen Docker file
          command: |
            ./build.sh << parameters.docker-tag >>
            ls -la php-<< parameters.docker-tag >>
      - run:
          name: build Docker image
          command: |
            docker build -f php-<< parameters.docker-tag >>/Dockerfile \
              -t $IMAGE_NAME:<< parameters.docker-tag >> \
              ./php-<< parameters.docker-tag >>
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            ./compile.sh p << parameters.docker-tag >>

workflows:
  run-node-tests:
    jobs:
      - build-and-publish:
          matrix:
            name: test-<< matrix.test-dir >>
            parameters:
              docker-tag: ["8"]
