version: 2.1

executors:
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps:18.04

jobs:
  build-and-publish:
    parameters:
      test-dir:
        type: string
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: build Docker image
          command: |
            ./compile.sh b
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            ./compile.sh p 

workflows:
  run-node-tests:
    jobs:
      - build-and-publish:
          matrix:
            name: test-<< matrix.test-dir >>
            parameters:
              test-dir: ["./"]
