#!/usr/bin/env sh
set -e

if [[ $(echo "$VERSION <= 7.1" | bc -l) == 1 ]]; then
  composer global require phpunit/phpunit 4.8.36
elif [[ $(echo "$VERSION <= 7.2" | bc -l) == 1 ]]; then
  composer global require phpunit/phpunit 8.5.52
elif [[ $(echo "$VERSION <= 8.0" | bc -l) == 1 ]]; then
  composer global require phpunit/phpunit ^9.6
elif [[ $(echo "$VERSION <= 8.2" | bc -l) == 1 ]]; then
  composer global require phpunit/phpunit ^10.5
elif [[ $(echo "$VERSION <= 8.3" | bc -l) == 1 ]]; then
  composer global require \
    phpunit/phpunit ^12.5 \
    php-coveralls/php-coveralls
  ln -s /.composer/vendor/bin/php-coveralls /usr/local/bin/coveralls
else
  composer global require phpunit/phpunit ^13.0
fi
